import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h1 {
            font-size: 3.5rem;
          }
        `}
      </style>
      <Head>
        <title>Crazy Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, crazycoder blog, crazy code" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan">Crazy Coder</span>
        </h1>
        <div className={styles.imageWrapper}>
          {/* <Image
            src="/home-img.jpg"
            alt=""
            width={240}
            height={160}
            className={styles.myImg}
          /> */}
          <img
            src="/home-img.jpg"
            width={240}
            height={160}
            className={styles.myImg}
            alt="home image"
          />
        </div>
        <p className={styles.description}>
          A blog for crazy coders by a crazy coder. Lorem ipsum dolor sit amet
          consectetur adipisicing elit. Magnam sequi ipsum, praesentium aliquam
          excepturi corrupti doloribus inventore maxime voluptate perferendis,
          modi aspernatur vitae, qui amet dolorum numquam voluptas explicabo
          perspiciatis.
        </p>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        {/* <div className={$`{styles.container}`}> */}
        <div>
          <h2 className={styles.h2}>Popular Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p>Javascript is a language used to design logic for web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p>Javascript is a language used to design logic for web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2022</h3>
            <p>Javascript is a language used to design logic for web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
